name: MCAds
main: net.MCAds.advertisements.Main
version: 0.0.1
description: >
             Ads on your server
commands:
  mcads:
    description: MCAds base command
    usage: "/mcads reload | holo [create|delete]"
  getlink:
    description: Gets referral link from current ad
    usage: "/getlink [scoreboard | bossbar]"
permissions:
  mcads.bypass.*:
    description: Disable all ads except holographic
    default: false
  mcads.bypass.bossbar:
    description: Disable bossbar ads
    default: false
  mcads.bypass.chat:
    description: Disable chat ads
    default: false
  mcads.bypass.scoreboard:
    description: Disable scoreboard ads
    default: false
  mcads.admin:
    description: Gives access to admin commands
    default: false

softdepend: [HolographicDisplays, BarAPI]