name: MCAds
main: net.MCAds.advertisements.Main
version: 1.2.0
description: >
             Ads on your server
commands:
  mcads:
    description: MCAds base command
    usage: "/mcads reload | holo [create|delete]"
  getlink:
    description: Gets referral link from current ad
    usage: "/getlink [scoreboard | bossbar]"

softdepend: [HolographicDisplays, BarAPI]