# This is the config file for MCAds
# If you would like to learn about the config or what any option does, read the configuration guide at http://polr.me/fa
paypal: email@example.com
language: en
featured: true
cache-expiry: 5
images: true
scoreboard:
    enabled: true
    delay: 30
bossbar:
    enabled: true
    delay: 15
chat:
    enabled: true
    delay: 60
hologram:
    enabled: true
    delay: 30